spring.application.name=fittrack-api
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/fittrack
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect